### ISSUE TITLE
branches in deployment selection is not complete

### ISSUE THREAD

**Issue by zhigang1992** [integrations/slack#1023]
We have over 100 branches, but on deployment we only see around first 15 or so

**Comment by jules2689** [comment]
Hi @zhigang1992,

Thanks for filing the issue 😄 
Unfortunately due to limitations in Slack, we can only show you the first 50 branches and 50 tags in that list.

This said, I am surprised to hear that only 15 are being shown. Are these branches all active and not stale? Can you share a but more information about the repository, the branches you expect to see, etc? If you aren't comfortable sharing this publicly, you could always reach out to our GitHub support team :)

Thanks!

**Comment by zhigang1992** [comment]
I see, as long as it's a know issue it's fine. 😄
