### ISSUE TITLE
Can't subscribe to organisation with dash in its name

### ISSUE THREAD

**Issue by guanchzhou** [integrations/slack#1089]
It is to possible subscribe to Nike-Inc organisation with the following command:

`/github subscribe Nike-Inc/gimme-aws-creds`.

Bit just raising the next error message:

`Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
Note: You need to be an organization owner to install the app (or ask one to install it for you).`

Subscribing to other organisations/repositories is working.

**Comment by FelipeR2U** [comment]
Same with `/github subscribe google/model-viewer`

**Comment by guanchzhou** [comment]
For some reason I can't subsrcibe to derailed/k9s even it has no dashes in the name.

**Comment by miguelTI** [comment]
In order to be able to subscribe to a repository the owner of that repository must install the Slack integration to allow it to send the notifications. In this case it must be that neither Nike-Inc, google and derailed have this installed. Please verify with the organization owner if they haven't done this instalation or there is any problem with the integration.

I have both an organization and various repositories with dashes on the name and it works fine.

**Comment by guanchzhou** [comment]
Thanks a lot for an explanation. This ticket may be closed then.

Andrey
27 нояб. 2020 г., 19:53 +0300, Miguel Alemán <notifications@github.com>, писал:

**Comment by dchopson** [comment]
This is an issue for me with a private repo that my organization owns: "ISOmodel-cove"

**Comment by miguelTI** [comment]
@dchopson have you installed the Slack integration in the organization's github ?

**Comment by amitkumariiit** [comment]
To subscribe to org/repo you need to install the github in the repo following the link posted on running subscribe command. Post that you should be able to subscribe. Closing this as @guanchzhou is able to do this
