### ISSUE TITLE
`/github deploy` is gone in the new App

### ISSUE THREAD

**Issue by torbjornvatn** [integrations/slack#1150]
I upgraded to the new version of the app today and all of a sudden the `/github deploy` command is gone.
Which is unfortunate since we use it for all our deployments.

Relates to #1147

**Comment by ashokirla** [comment]
@torbjornvatn We apologize for the inconvenience. We are taking a relook at the deploy functionality as the current experience is limited and doesn't address all the scenarios and we see very little adoption. We have removed deploy command support as part of the new version. We will evaluate the feedback and then build a holistic experience that customers need. 

It would be great if you can share your scenarios/requirements around deploy.

**Comment by reidab** [comment]
We were also relying on this `deploy` functionality and were surprised today when it was gone.

I've always been a bit confused by GitHub's approach to deployments. The API is well-defined and works nicely, but there seems to be a strong resistance to putting a button that creates deployments anywhere in the UI. This Slack integration was a nice workaround for that without having to maintain our own tooling for simple projects.

In terms of our workflow/requirements, they're pretty simple:

* creating a deployment triggers deploy tasks to run in GitHub actions
* those tasks update the status of the deployment as they run
* it was nice to have a trivial UI to kick them off

**Comment by torbjornvatn** [comment]
What @reidab just wrote! That's exactly what we used it for as well.

We have other ways to trigger the deploy though, but the missing deployment event messages in Slack is worse since we don't get any visual feedback that a deployment has started, failed or completed. So now we have to open the github repo for each project to see how the deployment is progressing.

**Comment by ncthbrt** [comment]
We were also using deployments for this scenario. 

This bit was especially relevant and was the main reason why we adopted the slack integration: 

> I've always been a bit confused by GitHub's approach to deployments. The API is well-defined and works nicely, but there seems to be a strong resistance to putting a button that creates deployments anywhere in the UI. This Slack integration was a nice workaround for that without having to maintain our own tooling for simple projects.

**Comment by reidab** [comment]
FWIW: we ended up working around this a [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) trigger to the relevant workflows and using https://github.com/bobheadxi/deployments to create deployments from within the workflow instead of triggering the workflow on deployment creation. Still, +1 to continued support of deployments in the Slack app for lightweight chatops without running additional tools.

```
name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "staging"
```

**Comment by alexleone** [comment]
+1 we use it to deploy our apps and had to downgrade back to the legacy for now.

**Comment by defg** [comment]
We also used the deploy functionality daily. It was by far the most useful feature of the Github App.

Used in the same manner as @reidab except using Buildkite instead of Github Actions.

**Comment by phuongnd08** [comment]
What is the recommended way to bring back the legacy integration for now? We miss the heroku deployment notification come with the legacy integration (https://github.com/integrations/slack/issues/1198)

**Comment by ashokirla** [comment]
Based on the customer feedback, we have decided to bring back deployment notifications functionality in the new slack app. This should be available very soon. 

Regarding the `/github deploy` command, we are relooking at the command experiences overall. Through our GitHub app, we want to empower users to perform various actions. As part of this effort, we will bring back deploy command along with additional capabilities.

**Comment by santoshD93** [comment]
@ashokirla 
Thanks for the update. Super looking forward to it and using GitHub instead of Heroku ChatOps to be notified about deployments.

**Comment by wushujames** [comment]
@ashokirla : If we want to get notification when deployment notifications are back, what is the best way to do that? Is subscribing to this issue enough?

**Comment by ashokirla** [comment]
Hi Everyone,

Yes, as we have promised, we have brought back the deployment notifications. It has been deployed few days back. Since it is a feedback, we couldn't do another changelog. Just like the old flow, deployment notifications is a default enabled feature i.e. you will receive deployment notifications once you subscribe to a repo. So, incase you don't want deployment notifications, you might have to unsubscribe the feature explicitly. This is a one time thing and we couldn't avoid this. We apologize for any inconvenience caused.
Incase if you are currently on old app and now you are planning to upgrade, the old configuration will be carried over i.e. you will not get deployment notifications if you unsubscribed for them in the old app. But if you are already on new app, you need to unsubscribe again.

We are working on a separate project to introduce various action commands. The deploy command will enabled as part of it with more improvements.

Let us know if you have any queries.

Thanks

**Comment by 0xdevalias** [comment]
@ashokirla Is there a repo/issue we can follow for updates on the new project for implementing the action commands at all?

**Comment by JCMais** [comment]
Hey @ashokirla are there any updates regarding the chatops commands to trigger GitHub actions from within Slack?
