### ISSUE TITLE
Checks show failing even though they passed

### ISSUE THREAD

**Issue by rafi-fisker** [integrations/slack#1194]
**Describe the bug**
Getting `No checks have passed 0/1 successful checks` even though the check passed

**To Reproduce**
1. Create github action on PR

**Expected behavior**
Checks should show as passed

**Screenshots**
![image](https://user-images.githubusercontent.com/72412693/116421065-5f23b800-a7f3-11eb-8f34-b7379bc8ec84.png)
![image](https://user-images.githubusercontent.com/72412693/116422870-048b5b80-a7f5-11eb-9b7a-08847fb52e34.png)

**Additional context**
We upgraded the Github app from the "legacy" one

**Comment by ashokirla** [comment]
@sushmita-m to look into this issue.

**Comment by sushmita-m** [comment]
@rafi-fisker was occupied with other issues, couldn't prioritize this. Sorry for the late reply.
Are the checks not being updated consistently?
Does your organization/repo have lot of activity going on? Asking because it could be rate-limit related on Slack API or GitHub API.

To come to a definite answer, I need more details from you. Can you run a `\github debug` command on your channel and send us the details by logging a ticket at https://support.github.com/contact

**Comment by rafi-fisker** [comment]
@sushmita-m actually, it seems to be working correctly now. maybe was a temporary glitch?

**Comment by rafi-fisker** [comment]
Spoke too soon, it's still happening, albeit intermittently. I'll open a ticket

**Comment by gauravsaralMs** [comment]
@rafi-fisker : just a quick update from our side, in past 2 days we have pushed 2 fixes to make sure checks status update works properly.
Do let us know in case you continue to see this issue, and if possible share the link of PR where you faced issue (if needed via support)

In case you are not facing the issue any more then please do close this issue.

**Comment by rafi-fisker** [comment]
@gauravsaralMs Sorry for the delay. Everything looks good, we haven't seen the issue at all recently. Closing!
