### ISSUE TITLE
This integration can't be installed if quota-minus-one slack apps are already installed in the workspace

### ISSUE THREAD

**Issue by rulatir** [integrations/slack#1250]
**Describe the bug**
This integration cannot be installed in a slack workspace that uses the free plan if there are already 9 apps installed, i.e. one fewer than the free plan quota.

**To Reproduce**
1. Create a slack workspace on a free plan
2. Go to app management
3. Install 10 apps different than this one to fill the quota
4. Uninstall one app to free up one quota slot
5. Go to slack.github.com and click the green "Add to Slack" button.

**Expected behavior**
The installation of the app in the workspace should succeed.

**Screenshots**
A message is displayed saying that the workspace cannot install more apps (the quota of 10 is explicitly mentioned) and offering a plan upgrade.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 89.0.2

**Additional information**
I hit this issue when trying to upgrade the legacy GitHub integration. I first received the over quota message when my quota **was** in fact filled. Then I removed the legacy GitHub integration, and now there are only 9 entries in the installed apps listing, but I still receive the over quota message when I try to install the new GitHub app.

**Comment by sanjeev9160** [comment]
@rulatir I followed the repro steps.

Steps to repro:
1. Installed 9 apps in a slack with free plan. 
![image](https://user-images.githubusercontent.com/64134945/124456435-4eba2b80-dda8-11eb-8f86-8e5765ed8d57.png)

2. Installing any other app gives me the over quota message.

So the issue seems to be on the slack free plan. Closing the issue. Thanks.
cc: @ashokirla

**Comment by brianmykietkaecra** [comment]
@sanjeev9160 This appears to still be an issue, so I'm unsure as to why this was closed? I hit the exact same problem when attempting to update my Github integration from Legacy to the new version. We have 9 installed and it will not allow me to re-install the new Github app.

**Comment by sanjeev9160** [comment]
@brianmykietkaecra I have closed it since it is unrelated with github integration app. Please see this comment. https://github.com/integrations/slack/issues/1250#issuecomment-874006512 

I have tried reproing the issue without installing github integration app. So the issue seems to be on the slack free plan. Closing the issue. Thanks.
