### ISSUE TITLE
PR review requests for a team do not tag that team or its team members in slack

### ISSUE THREAD

**Issue by sam-hoffman** [integrations/slack#1363]
If I make a PR and request review from some teammates specifically, the Slack integration will tag those teammates in the PR opened message. However, if I make a PR and request review from a team containing those teammates, no one gets tagged in the PR opened message. How can I make sure that people get tagged when I request review from a team?

**Comment by apurva1112** [comment]
Hi @sam-hoffman, at mention for team is not supported yet and only the individual PR reviewers will be mentioned. This is because a slack user connects his/her account individually to the corresponding GitHub account, which we use to mention the specific user. There is no mapping from slack team to GitHub team.
