### ISSUE TITLE
Add support for real time notifications of @mentions on issues

### ISSUE THREAD

**Issue by chrisalbrecht** [integrations/slack#1403]
**Is your feature request related to a problem? Please describe.**
Real time notifications do not work for @mentions on Github **issues**.

**Describe the solution you'd like**
I'd like to receive push notifications when I'm @mentioned on an issue comment, just like I am on PR comments.

**Describe alternatives you've considered**
The only alternative I'm aware of is Gmail filters, but I want real time notifications in slack.

**Additional context**
There is a [related issue](https://github.com/integrations/slack/issues/380), but it's over 4 years old and hasn't been addressed. I think it's too generic, so I've created a new issue for this specific feature request in hopes that it will be addresssed.

**Comment by ashokirla** [comment]
@chrisalbrecht , we have introduced @ mentions support this year. If you subscribe for Issues and comments features (in channel or personal chat) you will get mentioned in slack whenever someone refers to you in a GitHub comment.

**Comment by tpostappf** [comment]
@ashokirla this seems to still be an issue despite this being "closed"

**Comment by Chekote** [comment]
@ashokirla having to subscribe to issues and comments defeats the purpose. I don't want to be notified of all messages on the issue, I only want to be notified when I am explicitly tagged.

This feature is indeed still broken, so this either was not fixed, or was broken again since it was fixed. There is another open issue with the same complaint that seems to have been ignored: #1669
