### ISSUE TITLE
Not receiving notifications about PRs created by bot

### ISSUE THREAD

**Issue by dmcgrawFMP** [integrations/slack#1532]
I recently added renovate to a repository to create pull requests when there are packages that have major updates available. Each pr is created with a label 'major-package-update'. I have set up the slack integration to notify a channel when there are any pull requests that have that label. 

I expected to be notified when the renovate bot created a pull request as I tested things by creating a pull request using the label and I was notified. However, since then the bot has created a couple of pull requests but there has been no notifications in the channel.

At first I wondered if I needed to set permissions to allow notification from a pr created by a bot but I can't find any documentation on this. I'm not sure if this is a bug or I am missing something?

**Comment by sanjeev9160** [comment]
@dmcgrawFMP Please help me understand few things:
1. Have you subscribed the org/repo using the subscribe command in the expected channel?
2. When you subscribe, you will also be asked to install the slack-integration github app to your org/repo. So please install it.
Thanks.

**Comment by dmcgrawFMP** [comment]
@sanjeev9160 Yeah I have subscribed and added the label filter. Yes I have also installed the app as I'm able to get notifications when I create a pull request in the repo that I have subscribed too but unable to receive notifications when a bot creates a pull request.

**Comment by sanjeev9160** [comment]
@dmcgrawFMP Thanks for the information. Will look into the issue and will keep you posted.

**Comment by sanjeev9160** [comment]
@dmcgrawFMP I tried digging more information through the logs and I don't see any log where we have successfully posted any event which has the required label as `major-package-update` in past 7 days. 
Can you please share when you have tested the notification for a PR with required label: `major-package-update`? In case if you haven't done please test once so that I can have some information to debug the issue. Thanks.

**Comment by dmcgrawFMP** [comment]
@sanjeev9160 Hi sorry the label is actually `major-version-update-needs-review`. I ran a couple tests today at 10:35am which worked but I done this as I was expecting notifications between 9:00am and 10:00am that I did not receive.

Sorry for letting you know the wrong label.

**Comment by sanjeev9160** [comment]
@dmcgrawFMP The reason is that the renovate is adding the label: `major-version-update-needs-review` after some time in the PR after PR is opened. 

How does it impact the notifications?
Once you have added the label filter(through subscribe command) then we filter the any event based on the filter.
So in this case when the Pull Request is opened by the renovat bot, we don't send the PR open card to slack as the label is not added in the PR when the PR is opened. 
Now after some time renovate bot adds the label. We do receive the `pull_request.labeled` event and try to update already existing Pull Request Opened card. But there is not Pull Request opened card, so nothing happens and hence you don't see any Pull Request card when opened by renovat bot.
But if you open a PR with label already added, this gets processed and you receive the PR card notification.

I will open a backlog item to support the scenario where labels are added after PR is opened. Thanks.

**Comment by sanjeev9160** [comment]
Closing it as the backlog item will address the issue.
