### ISSUE TITLE
Slack "double-check this link" now triggers on all embeds due to `#`

### ISSUE THREAD

**Issue by mscoutermarsh** [integrations/slack#1854]
It seems slack has recently changed their behavior and now always shows a `double-check this link` warning when clicking any unfurl that starts with a `#`.

This makes clicking any pull request or issue unfurl from the GitHub + Slack app show the warning.

<img src="https://github.com/integrations/slack/assets/155044/7902d032-31e8-4714-ab57-a68eb9796ded" width="500px"/>

<img src="https://github.com/integrations/slack/assets/155044/18fdb693-79bf-498d-9597-af16e349231a" width="500px"/>

I found this reference on [reddit](https://www.reddit.com/r/Slack/comments/ezwwig/doublecheck_this_link_prompt_every_time/)

> If anyone else ever Googles this and can't figure out the issue the problem occurs when links to external sites begin with a # mark. I assume this is to stop people clicking links that look like they are to internal Slack channels being taken to malicious third party sites.

**Comment by jezcommits** [comment]
👋 that's interesting because we link every PR and issue with the `#` 😅. I think we cannot avoid that alert and we should decide whether to remove the `#` or not from all the links. This decision should escalate to product. Change should not be super difficult so I will triage accordingly:

Based on our [triage process](https://github.com/github/notifications/blob/master/docs/on-call-FR/customer-escalations-triage-process.md) we've assigned this issue the following priority:

| Impact | Severity | Effort | Priority |
| ---- | ---- | ---- | --- |
| High | Low | Low | 2 |

If you have additional details that could change this issue's priority, please follow up here so we can revisit.


cc @jlord

**Comment by mscoutermarsh** [comment]
Hi! Update: I've heard from Slack that they are fixing it on their end. 😄

**Comment by jezcommits** [comment]
awesome! Thanks for the update. Closing this issue

**Comment by Mosafer6066** [comment]
[Contribution guidelines for this project](docs/CONTRIBUTING.md)

**Comment by Mosafer6066** [comment]
[Contribution guidelines for this project](docs/CONTRIBUTING.md)

**Comment by broksonic21** [comment]
This is still continuing and happening on every click - any word back from Slack or additional way to solve?

**Comment by mscoutermarsh** [comment]
Same, I haven't heard anything from them.

**Comment by jlord** [comment]
I'm reaching out to see if I can get an update and will re-open this as it's still an issue.

**Comment by jlord** [comment]
They got back to me already and it is known/tracked on their end and being worked on. They'll let me know when it's resolved 👍

**Comment by jlord** [comment]
It should be resolved now they said 🎉
