### ISSUE TITLE
Ability to filter on only showing new pull requests / merges

### ISSUE THREAD

**Issue by larsjoakimgrahn** [integrations/slack#406]
We use the pull notifications as a backlog of what to review. Would be nice to be able to choose a finer granularity for notifications of pull requests, for example 
`pulls:new`
`pulls:merge`

Either that or being able to choose updating the color of merged PRs to purple ones instead of receiving a new notification.

**Comment by mikesigs** [comment]
#510 appeared to be what I was looking for, but it was closed as a dup of this issue. Specifically, I would like to see all activity related to a PR appear as thread replies to that PR's thread. If that doesn't sound like what this issue is supposed to solve, please let me know. I will create a new issue.

**Comment by larsjoakimgrahn** [comment]
This is still relevant. I like the solution from #510 with threading.

**Comment by adamwiggins** [comment]
Our team would like a `pulls:merged` option. We treat merges to master as mini-releases and want a separate channel just for those.

**Comment by gordontucker** [comment]
The solution for this mentioned in #510 sounds like it would be amazing and keep our channel way cleaner.

**Comment by abinoda** [comment]
@gordontucker Have you looked into doing this using a custom [GitHub Workflow](https://github.com/actions/)? I created a starter Action that handles posting to Slack – https://github.com/pullreminders/slack-action – all you'd have to do is create a workflow that subscribes to the specific events you want notifications for.

**Comment by amadeu01** [comment]
It could be nice to add some sort of filter to a tag, so for a large codebase, a PR could go to different channels depending on their tags.

**Comment by scepticulous** [comment]
Hey everybody 👋 

I think implementing arguments for `pull` as suggested by @larsjoakimgrahn sounds like a feasible solution to the described problem.
I suggest the following to options: `pulls:opened` and `pulls:closed`, so that the argument matches the [event action](https://developer.github.com/v3/activity/events/types/#pullrequestevent).

Please let me know if this would work for all of your use-cases. If not, please let me know.

**Comment by scepticulous** [comment]
Closing in favor of #519, since it asks for the same features.
Please check out that other issue and if your use-case is not covered there, consider commenting there or creating a dedicated issue, if necessary.
