### ISSUE TITLE
Show build status with commit notification

### ISSUE THREAD

**Issue by xt0rted** [integrations/slack#416]
If I create a PR two messages show up in slack, one about the PR being opened and another showing the build status of the PR. Once the build is finished the status is updated accordingly. If I then push more changes to this branch the build status doesn't change to pending/success/failed, and no new message comings in showing the new build that's currently going. It'd be nice to see the most recent build/check statuses after a new push.

**Comment by bkeepers** [comment]
Hi @xt0rted, thanks for open an issue.

The behavior you're seeing is actually intentional. We only update messages for the first 30 minutes after they are posted. I [opened an issue](https://github.com/integrations/slack/issues/417) to remind us to document this and explain our rationale, but the TL;DR is we wanted to rollup related activity without generating more noise, but also wanted the history to reflect reality at the time. For example, it would be confusing to look back at a discussion about why the build was failing if the notification was later updated to passing.

I think it would make sense to include build status on the `commits` and `commits:all` notifications so statuses are shown whenever commits are pushed.

I updated the title of this issue to reflect that direction. Let me know if you have any feedback on that.

**Comment by xt0rted** [comment]
Showing statuses along with later commits/pushes is what I was envisioning. A lot of times I'll create a PR and continue pushing to it (sometimes over multiple days), so seeing those later statuses is really useful. How would this work if I rebased and force pushed? Would there be a notification & status message for that as well?

**Comment by bkeepers** [comment]
> How would this work if I rebased and force pushed? Would there be a notification & status message for that as well?

Yeah, I think we would show statuses whenever commits were pushed.
