### ISSUE TITLE
Consolidate review comments into a single message

### ISSUE THREAD

**Issue by atopiler** [integrations/slack#493]
The legacy integration consolidated all comments within a single PR review into a single Slack notification with multiple attachments.  

This new integration turns each individual review comment into an individual slack notification, completely spamming up the slack channel.  

Can we please consolidate all PR review comments into a single slack notification again?  This was so much more useful in the legacy integration! The current implementation is almost unusable because of all of the noise 😔

**Comment by bkeepers** [comment]
Thanks for the feedback, @atopiler! I agree that would be really nice. Improvements to review comment notifications aren't high on our list of priorities for the next month or two, but we'd be happy to review a pull request that makes changes to reviews.

If anyone wants to dig into it, we'd be happy to answer questions or help in any way.

**Comment by AndrewSouthpaw** [comment]
Any chance this could be prioritized at some point? We keep getting spammed every time someone submits a review. 😂

**Comment by debdeepmajila** [comment]
Can we please reopen and prioritize this?
Spamming definitely makes the feature unusable.

**Comment by bpartridge** [comment]
Does anyone have any workarounds here? I think the ideal outcome is:

- If a standalone comment (not part of a review) is placed on a PR it should notify standalone.
- If a comment is part of a review, it should not notify for that comment itself; there should only be a single notification for the e.g. "Reviewed and changes requested by X on Y's pull request" with the content of the overall review message!

Simply turning off notifications for comments would cause us to miss notifications for standalone comments, which are often added because "this is important to address even in advance of a full code review".

On the flip side, when we hear a `knockknockknockknockknockknockknock` late at night or on a weekend, it means someone was motivated to do a huge code review that late, which I suppose shows that the team is dedicated!

But it can also be dangerous as a cry-wolf for anyone who happens to be on-call at that time, and encourages people to mute the e.g. #github-notifications channel when they otherwise wouldn't or shouldn't (arguably the person on-call should receive exactly 1 notification that a comment was made, in case it is relevant to an ongoing situation - not zero and not fifty). It's a real problem that we feel every day.

**Comment by AndrewSouthpaw** [comment]
For me I just had to turn it off. I now only rely on email notifications and it's much more async than before. 😞
