### ISSUE TITLE
Some PR creation/open notifications are not appearing

### ISSUE THREAD

**Issue by DannyNemer** [integrations/slack#496]
In the last week, at least seven pull request creation/open notifications for my organization did not appear in the Slack channels subscribed to the corresponding repositories. Most PR creation/open notifications do come through; some are arbitrarily absent. All other GitHub notifications (e.g., comments, merges, commits) come through. I can not determine the characteristics or unifying pattern amongst those PRs failing to notify.

Is this issue already known? If not, what information can I provide to help debug?

Thank you very much. My team immensely appreciates your work.

**Comment by bkeepers** [comment]
Hey @DannyNemer, thanks for reporting the issue, and for the compliments!

We've seen an elevated rate of errors the past couple days and have been trying to track it down. It appears related to replication lag on GitHub (we receive the webhook event and try to look up data about the event, but GitHub returns an error because the API can't find the error)

I just deployed #494, which is an attempt to fix it. Initial monitoring shows that it is significantly improved (but still not solved). Let us know in the next day or so if you're still seeing issues and we'll open this back up to investigate more.

**Comment by DannyNemer** [comment]
Thank you, @bkeepers!
