### ISSUE TITLE
Issue bodies don't seem to truncate like PR bodies

### ISSUE THREAD

**Issue by lee-dohm** [integrations/slack#547]
Example issue:

<img width="698" alt="screen shot 2018-04-19 at 8 52 32 am" src="https://user-images.githubusercontent.com/1038121/39003794-791851bc-43b0-11e8-821f-10c37fff49f5.png">

Notice no "show more" link.

Example PR:

<img width="699" alt="screen_shot_2018-04-19_at_8_52_48_am" src="https://user-images.githubusercontent.com/1038121/39003905-c5f14f20-43b0-11e8-8896-320a0d2aa8ed.png">

**Comment by wilhelmklopp** [comment]
@lee-dohm I believe the truncating is done based on character count, not number of lines. Although I agree it should be based on number of lines. We'll raise this to Slack

**Comment by lee-dohm** [comment]
Thanks @wilhelmklopp! Is the character count configurable by the integration? Or is it done solely on the Slack side?

**Comment by wilhelmklopp** [comment]
Solely on the Slack side unfortunately

**Comment by bkeepers** [comment]
Thanks for reporting the issue, @lee-dohm. I really wish we had more control over the message formatting. I'm going to close this since there isn't much we can do immediately, but we'll pass some feedback on to Slack and see if there's ever any way we can truncate it ourselves.

In the mean time, we might want to add the ability to only deliver condensed messages (#162)
