### ISSUE TITLE
In the message list the `Reviewers` under `Assignees` field when PR is opened

### ISSUE THREAD

**Issue by smoke** [integrations/slack#655]
This is a new feature request, namely to have the list of `Reviewers` in addition and similar to how `Assignees` are shown here:
![image](https://user-images.githubusercontent.com/196165/43884210-2ab738a6-9bbe-11e8-8584-dee33beefd1c.png)

**Comment by gimenete** [comment]
@smoke good idea. I've been working on this today on #684

@doms thanks for your code! I've implemented something similar to what you were doing. Since the context is not available in `PullRequest` because it seems to be mainly intended to be used for composing the slack message rather than fetching information, I'm passing the information to it and fetching it in the previous step, that has access to the context object.

**Comment by doms** [comment]
@gimenete 👋 

> Since the context is not available in PullRequest because it seems to be mainly intended to be used for composing the slack message rather than fetching information

Ohh okay, that makes sense! 

> I'm passing the information to it and fetching it in the previous step, that has access to the context object.

Sounds good! Can't wait to see your implementation, maybe I can learn a few things 👀

**Comment by smoke** [comment]
@gimenete Thank you for making this happen!!!
