### ISSUE TITLE
GitHub App not giving notifications in Slack

### ISSUE THREAD

**Issue by EyeCandyEyewear** [integrations/slack#723]
I've connected Slack to my GitHub Organization, I've connected the GitHub App to our Slack, invited it to our `#channel`, running `/github subscribe Organization/Repo` gives me a positive reply that the channel is now subscribed.

The repository's under the organization are private, so I'm not sure if that is the reason why but we are receiving no notifications when a commit is made, whether to `master` or any other branch.

I've read [#679](https://github.com/integrations/slack/issues/679) and running `/github subscribe list` shows the repository as it should.

Have also seen [#625](https://github.com/integrations/slack/issues/625) which I was linked to from [#641](https://github.com/integrations/slack/issues/641) with no luck.

**Comment by andymckay** [comment]
There's an ongoing incident at this time https://status.github.com/messages and that might be causing a problem with webhook deliveries, or delays as the backlog processes.

**Comment by tcbyrd** [comment]
The message above from `welcome [bot]` would normally be delivered as soon as the issue was open. This is also related to backlog in webhook deliveries. @EyeCandyEyewear You should start seeing messages in Slack once GitHub webhook deliveries catch up. We just started seeing some messages from 3-4 hours ago, as an example.

**Comment by EyeCandyEyewear** [comment]
Wow, what timing! I was assuming that I messed something up in the configuration. I guess this issue can closed, thanks for the info!
