### ISSUE TITLE
Commands with a link seem to post twice

### ISSUE THREAD

**Issue by IAmHughes** [integrations/slack#870]
@tarebyte @wilhelmklopp and I were working on #857 and through testing, discovered this existing bug in the production environment.

![image](https://user-images.githubusercontent.com/2894107/59800106-64388780-92ab-11e9-8b7f-ca2f1d84cd54.png)

~It appears that the link is unfurling~ It seems like there's a bug in `issue-state` perhaps, getting the subscription event for an issue being opened as well as an output for the command.

/cc @gimenete @swinton @imjohnbo @eekdageek

**Comment by wilhelmklopp** [comment]
> It appears that the link is unfurling,

I _believe_ it's not unfurling because for that the UI would look a little bit different (no "issue opened by" text, and so on).

But I think there's a bug in `issue-state` somewhere that leads to the double posting in case there's already a subscription in the channel where the `/github reopen` command is being run
