### ISSUE TITLE
[Feature Request] Deployment parameters / errors 

### ISSUE THREAD

**Issue by iboobel** [integrations/slack#984]
We are trying to use deployments via slack. 
We faced a few issues: 
- can't set additional deployment parameters (like auto_merge or required_contexts  https://developer.github.com/v3/repos/deployments/#create-a-deployment)
-  can't see why deploy wasn't run. E.g.:  if the status check is false, the deploy will not run and slack doesn't show the reason

**Comment by tebriel** [comment]
Thanks @iboobel. Deploys are one of our least-used features (we see less than 100 a day could be a chicken-egg situation where they're not what people need so they're not used) so they've been lagging in feature development. I don't think in the near-future we'll be able to add this requested functionality due to our other priorities (changing the infrastructure the app is deployed on and fixing some long-standing bugs). I very much like this idea, though.

**Comment by mkrakowitzer** [comment]
Would also like this feature built into the slack integration. 

It's listed in the help as a feature, but it just errors out and it's undocumented if it accepts any parameters at all such as environment etc.

```
/github deploy owner/repository
```
@iboobel it looks like you have limited success with the deployments, if you could give me some pointers on how it to use them would appreciate it.

**Comment by tebriel** [comment]
@mkrakowitzer when you issue a `/github deploy owner/repo` it will (should, except in the case of an error) open up a Slack Dialog to allow you to pick some default options. Screenshot attached, sorry it isn't working for you.
![Deployment Dialog](https://user-images.githubusercontent.com/821688/73672487-f21a8480-467a-11ea-907a-aa4846b35741.png)

**Comment by shandyDev** [comment]
It actually strange: payload (very optional) have in dialog popup, but another 2 options (https://developer.github.com/v3/repos/deployments/#parameters-1):
- auto_merge
- required_contexts

It very important params because deployment (special in CI processes) should be start as is without action on codebase (merge) also without CI checks.
What all need IMHO, add fields to dialog and pass it to github api:
https://github.com/integrations/slack/blob/master/lib/messages/create/create-deployment-dialog.js#L58
https://github.com/integrations/slack/blob/master/lib/create/deployment.js#L38
